### ISSUE TITLE
Move relevant issues from 'datacarpentry' repo to 'planning' repo

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/planning#1]
It would be good to move the open issues from 'datacarpentry' to 'planning' or their other relevant repo. Github doesn't provide issue moving functionally though, so we need to use something else or do it manually.

**Comment by hlapp** [comment]
I wonder whether that's the best way of doing this. Here's an alternative proposal:
- Copy the 'datacarpentry' repo as an act of preservation, under a prefixed name where the prefix clearly suggests that this is only for archival purposes. (Right now you have to go and read the README to know that it's legacy only.) This could be done using Github's import feature.
- Subsequently rename the 'datacarpentry' repo to 'planning' (and obviously delete this one first).

Doing this is only a few clicks through the Github UI, preserves everything we'd like to preserve, and maintains the issue tracker threads without requiring any additional manual work. And folks who had bookmarks for the datacarpentry issue tracker will be redirected here for the right reasons, rather than landing on an issue tracker that they may not realize is defunct by implication.

**Comment by tracykteal** [comment]
I've already seen some confusion about the 'datacarpentry' repo. I had just updated the README in response to that.

I like the idea @hlapp proposes as a solution to the archiving and the issues, as long as it's standard enough github practice.

**Comment by ethanwhite** [comment]
The downside to this is that our planning repo has a bunch of material in it, which seems a bit confusing and will make it more difficult to use the repo itself for add actual planning related documents to.

The other upside to @hlapp proposal that isn't listed is that the planning repo will keep all of followers from the datacarpentry repo.

In aggregate I'm -0 on this.

**Comment by hlapp** [comment]
> The downside to this is that our planning repo has a bunch of material in it, which seems a bit confusing and will make it more difficult to use the repo itself for add actual planning related documents to.

If by _this_ you mean the proposal I'm making, this need not be the case at all. We can delete anything not applicable to the new "planning" purpose, because with the separate archival copy there is no need to keep stuff solely for archival purposes.

**Comment by fmichonneau** [comment]
+1 on @hlapp proposal

**Comment by tracykteal** [comment]
also +1 on @hlapp proposal, and I say let's go ahead, since this issue has been open a while and there hasn't been dissent. @hlapp can you do this?

**Comment by hlapp** [comment]
> I say let's go ahead, since this issue has been open a while and there hasn't been dissent. @hlapp can you do this?

I can, except it turns out I was too optimistic (or naïve) as to what Github import is able to do. After all, it _doesn't_ copy the issues and pull requests, but only copies the _repo_. So while we could archive the datacarpentry repo in this way, it would lack all issue and pull request history, so wouldn't be a perfect archive. Note that we would _not_ lose the issues and pull requests, because the _rename_ of the repo (which is step 2 in my proposal) would still keep all of them. They would just be missing from the archive.

So in order to have a better comparison, I did finally look at how you would move issues from repo to another. Github unfortunately doesn't provide a function that does this, but it provides an API, and there are a few scripts and online tools out there that use it for this purpose. However, the API doesn't allow you to do things that could otherwise be considered sinister, such as acting in the identity of another user. This means that an issue that's being moved in reality gets copied, and thus necessarily created under the identity of the user doing the move, with current rather than original timestamp.

The original ownership of issue and issue comments is still evident, though. You can take a look at how this would look like here: datacarpentry/test#1 and datacarpentry/test#2. They were "moved" with the [github-issue-mover](https://github-issue-mover.appspot.com/). You will see that the tool leaves issue comments behind that link original and destination, and normally it will automatically close the original if it was open.

So in light of this, should we still go ahead with the plan as per my suggestion:

> - Copy the 'datacarpentry' repo as an act of preservation, under a prefixed name where the prefix clearly suggests that this is only for archival purposes. (Right now you have to go and read the README to know that it's legacy only.) This could be done using Github's import feature.
> - Subsequently rename the 'datacarpentry' repo to 'planning' (and obviously delete this one first).

Or should we then keep this repo, and "move" the open issues from the `datacarpentry` repo here? (Remember that doing so will _not_ leave a redirect from the `datacarpentry` repo URL to this one.)

**Comment by tracykteal** [comment]
Thanks for looking in to this. 

So, if we rename the datacarpentry repo to say archive-datacarpentry all the issues and pull requests will be kept in tact?

If that's the case then I would vote for 
- rename datacapentry to something like archive-datacarpentry
- move the open issues from datacarpentry here (planning) like how was done for the test cases

People on open issues are 
@hlapp @tracykteal @ethanwhite @fmichonneau @apawlik @areff2000

so, if we get +1s from them it should be OK

**Comment by areff2000** [comment]
+1 from @areff2000

On 17 April 2015 at 09:34, Tracy Teal notifications@github.com wrote:

> Thanks for looking in to this.
> 
> So, if we rename the datacarpentry repo to say archive-datacarpentry all
> the issues and pull requests will be kept in tact?
> 
> If that's the case then I would vote for
> - rename datacapentry to something like archive-datacarpentry
> - move the open issues from datacarpentry here (planning) like how was
>   done for the test cases
> 
> People on open issues are
> @hlapp https://github.com/hlapp @tracykteal
> https://github.com/tracykteal @ethanwhite
> https://github.com/ethanwhite @fmichonneau
> https://github.com/fmichonneau @apawlik https://github.com/apawlik
> @areff2000 https://github.com/areff2000
> 
> so, if we get +1s from them it should be OK
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/datacarpentry/planning/issues/1#issuecomment-93862245
> .

## 

dr Richard Ferrers
ANDS Data Specialist | Outreach Officer
formerly [ Research Data Analyst | Client Liaison Officer ]

Our Vision: More valuable data for Australian Research

Australian National Data Service (ANDS)
... enables better managing, connecting, discovering, and reusing research
data...
.... by supporting Research Institutions to achieve their data management
ambitions...
.... by maintaining and supporting Australia's world leading research data
environment...

Physical Address: Level 6, Building F, Monash Caulfield VIC 3145 AUSTRALIA
Postal Address: c/o Monash University, PO Box 197, Caulfield East, VIC 3145
AUSTRALIA
T: +61 3 990 20569
F: +61 3 990 20585
M: 0422 368 061
E: richard.ferrers@ands.org.au

**Comment by fmichonneau** [comment]
+1 from me too. Thanks for taking the time look into this @hlapp!

**Comment by hlapp** [comment]
I'm OK with this. Assuming that @tracykteal is too given that she's suggested it, this leaves @ethanwhite and @apawlik from whom we still have to get a :+1: .

**Comment by hlapp** [comment]
Ping to @ethanwhite and @apawlik.

**Comment by ethanwhite** [comment]
:+1:

**Comment by apawlik** [comment]
+1 (apologies for delay)

**Comment by hlapp** [comment]
Moved issues, and renamed `datacarpentry` repo to archive-datacarpentry. Two more things need to be cleaned up before this can be closed:
1. [x] There is an open pull request: datacarpentry/archive-datacarpentry#132. @kcranston should this be redirected to the [shell-ecology](https://github.com/datacarpentry/shell-ecology) lesson? If yes, can you comment there accordingly and close?
2. [ ] There is a wiki page titled _[Lesson template](https://github.com/datacarpentry/archive-datacarpentry/wiki/Lesson-template)_. @fmichonneau and @tracykteal is this in another format elsewhere now, or does this need to be carried over, and to where?

**Comment by fmichonneau** [comment]
I had created the wiki page for the hackathon in Finland. It seems that it should go to the wiki of the lesson-template repo. Any other suggestions?

**Comment by hlapp** [comment]
> I had created the wiki page for the hackathon in Finland. It seems that it should go to the wiki of the lesson-template repo.

That sounds right to me!

**Comment by kcranston** [comment]
Commented and closed [PR 132](https://github.com/datacarpentry/archive-datacarpentry/pull/132)

**Comment by hlapp** [comment]
Created datacarpentry/lesson-template#5 to track completion of the wiki page move. I'm closing this issue now.
